version: 0.2

phases:
  pre_build:
    commands:
      - DEFAULT_PATH=$(pwd)
      - AWS_MODULE_SOURCE=$(aws ssm get-parameter --name "/aft/config/aft-pipeline-code-source/repo-url" --query "Parameter.Value" --output text)
      - AWS_MODULE_GIT_REF=$(aws ssm get-parameter --name "/aft/config/aft-pipeline-code-source/repo-git-ref" --query "Parameter.Value" --output text)
      - |
        CUSTOMIZATION=$(aws dynamodb get-item --table-name aft-request-metadata --key "{\"id\": {\"S\": \"$VENDED_ACCOUNT_ID\"}}" --attributes-to-get "account_customizations_name" | jq --raw-output ".Item.account_customizations_name.S")
      - echo $CUSTOMIZATION
      - ssh_key=$(aws ssm get-parameter --name /aft/config/aft-ssh-key --with-decryption | jq --raw-output ".Parameter.Value")
      - mkdir -p ~/.ssh
      - echo "Host *" >> ~/.ssh/config
      - echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - echo "UserKnownHostsFile=/dev/null" >> ~/.ssh/config
      - echo "$ssh_key" > ~/.ssh/ssh_key
      - echo -e "\n\n" >>  ~/.ssh/ssh_key
      - chmod 600 ~/.ssh/ssh_key
      - eval "$(ssh-agent -s)"
      - ssh-add ~/.ssh/ssh_key
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - git clone -b $AWS_MODULE_GIT_REF $AWS_MODULE_SOURCE aws-aft-core-framework
      - chmod +x ./aws-aft-core-framework/sources/scripts/creds.sh
      - |
        if [ -d "$CUSTOMIZATION" ]; then
          echo "Found customization" $CUSTOMIZATION
          ./aws-aft-core-framework/sources/scripts/creds.sh --account-id $VENDED_ACCOUNT_ID
          python3 -m venv ./venv
          source ./venv/bin/activate
          pip install -r ./$CUSTOMIZATION/api_helpers/python/requirements.txt
          chmod +x ./$CUSTOMIZATION/api_helpers/$SHELL_SCRIPT
        fi
  build:
    commands:
      - |
        if [ -d "$CUSTOMIZATION" ]; then
          ./$CUSTOMIZATION/api_helpers/$SHELL_SCRIPT
        fi
  post_build:
    commands:
      - echo "Post-Build"
